name: test (python 2.7)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python: python2
            pip: pip
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install python dependencies
        run: |
          wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
          ${{ matrix.python }} get-pip.py
          ${{ matrix.python }} -m ${{ matrix.pip }} install --user --upgrade pip
          ${{ matrix.python }} -m ${{ matrix.pip }} --no-cache-dir install --user -e .[all]

      - name: Show python dependencies
        run: |
          ${{matrix.pip}} --version
          ${{ matrix.python }} --version
          ${{ matrix.pip }} freeze

      - name: Run tests
        run: |
          ./run-tests.sh