name: bump and publish

on:
  workflow_call:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bump2version
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Configure git
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Bump version
        shell: bash
        run: |
          bump2version patch --tag --verbose

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true


  publish:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools twine wheel coveralls
          pip install -e .[all]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Build package
        run: |
          mkdir clean-build
          python setup.py sdist bdist_wheel --universal --dist-dir ./clean-build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          packages_dir: clean-build/
